name: toly_menu
description: 面向 Flutter 桌面与 Web 的菜单组件，支持下拉、级联、上下文和菜单栏场景。
version: 0.0.1
homepage: https://github.com/TolyFx/toly_ui
repository: https://github.com/TolyFx/toly_ui/tree/main/modules/navigation/toly_menu

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
